# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/chat.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11protos/chat.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x1a\n\x07Mensaje\x12\x0f\n\x07message\x18\x01 \x01(\t2\x94\x01\n\nChatServer\x12)\n\x0bpassMessage\x12\r.grpc.Mensaje\x1a\x0b.grpc.Empty\x12.\n\x0e\x43ontrolMessage\x12\r.grpc.Mensaje\x1a\r.grpc.Mensaje\x12+\n\x0b\x41uthMessage\x12\r.grpc.Mensaje\x1a\r.grpc.Mensajeb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='grpc.Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.Mensaje.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJE,
  '__module__' : 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Mensaje)
  })
_sym_db.RegisterMessage(Mensaje)



_CHATSERVER = _descriptor.ServiceDescriptor(
  name='ChatServer',
  full_name='grpc.ChatServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=65,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='passMessage',
    full_name='grpc.ChatServer.passMessage',
    index=0,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ControlMessage',
    full_name='grpc.ChatServer.ControlMessage',
    index=1,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AuthMessage',
    full_name='grpc.ChatServer.AuthMessage',
    index=2,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVER)

DESCRIPTOR.services_by_name['ChatServer'] = _CHATSERVER

# @@protoc_insertion_point(module_scope)
