# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import chat_pb2 as protos_dot_chat__pb2


class ChatServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.passMessage = channel.unary_unary(
        '/grpc.ChatServer/passMessage',
        request_serializer=protos_dot_chat__pb2.Mensaje.SerializeToString,
        response_deserializer=protos_dot_chat__pb2.Empty.FromString,
        )
    self.ControlMessage = channel.unary_unary(
        '/grpc.ChatServer/ControlMessage',
        request_serializer=protos_dot_chat__pb2.Mensaje.SerializeToString,
        response_deserializer=protos_dot_chat__pb2.Mensaje.FromString,
        )
    self.AuthMessage = channel.unary_unary(
        '/grpc.ChatServer/AuthMessage',
        request_serializer=protos_dot_chat__pb2.Mensaje.SerializeToString,
        response_deserializer=protos_dot_chat__pb2.Mensaje.FromString,
        )


class ChatServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def passMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ControlMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'passMessage': grpc.unary_unary_rpc_method_handler(
          servicer.passMessage,
          request_deserializer=protos_dot_chat__pb2.Mensaje.FromString,
          response_serializer=protos_dot_chat__pb2.Empty.SerializeToString,
      ),
      'ControlMessage': grpc.unary_unary_rpc_method_handler(
          servicer.ControlMessage,
          request_deserializer=protos_dot_chat__pb2.Mensaje.FromString,
          response_serializer=protos_dot_chat__pb2.Mensaje.SerializeToString,
      ),
      'AuthMessage': grpc.unary_unary_rpc_method_handler(
          servicer.AuthMessage,
          request_deserializer=protos_dot_chat__pb2.Mensaje.FromString,
          response_serializer=protos_dot_chat__pb2.Mensaje.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.ChatServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
