version: "3"
services:
  server:
    build: ./server
    volumes:
      - ./server:/app/
    ports:
      - "50051:50051"

  client:
    build: ./client
    volumes:
      - ./client:/app/
    links:
      - server
    depends_on:
      - server
