version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    logging:
      driver: none
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  server:
    build: ./server
    volumes:
      - ./server:/app/
    ports:
      - "5000:5000"
    links:
      - rabbitmq

    depends_on:
      - rabbitmq
  client:
    build: ./client
    volumes:
      - ./client:/app/
    links:
      - rabbitmq
    depends_on:
      - server
